from __future__ import annotations

import json
import math
import time
from pathlib import Path


V41_PARAMETERS = {
    "K_bg_best": 1.0,
    "Sent_0": 0.9,
    "eta": 0.012,
    "gamma": 0.45,
    "Sent_inf": 0.7,
    "alpha": 0.12,
    "xi": 0.68,
}


def workspace_root() -> Path:
    return Path(__file__).resolve().parents[2]


def v41_result_dir(output_dir: str | Path | None = None) -> Path:
    base_dir = Path(output_dir) if output_dir is not None else workspace_root() / "results" / "result-analyse"
    return base_dir / "v41_symmetry_analysis"


def timestamp() -> str:
    return time.strftime("%Y%m%d-%H%M%SZ")


def write_report(json_path: Path, payload: dict[str, object]) -> None:
    json_path.write_text(json.dumps(payload, indent=2, ensure_ascii=True), encoding="utf-8")


def _sent_profile(z: float) -> float:
    return V41_PARAMETERS["Sent_inf"] + (V41_PARAMETERS["Sent_0"] - V41_PARAMETERS["Sent_inf"]) * math.exp(-V41_PARAMETERS["gamma"] * z)


def _k_bg_profile(z: float) -> float:
    return V41_PARAMETERS["K_bg_best"] * (1.0 + z) ** V41_PARAMETERS["alpha"]


def _effective_lagrangian() -> str:
    return (
        "L_eff = L_GR + L_K + L_Sent + L_mix; "
        "L_K ~ -(1/2) dK_bg^2, L_Sent ~ relaxation(Sent(Y)), L_mix ~ eta * Sent(Y) * K_bg"
    )


def _source_v40_summary() -> dict[str, object] | None:
    result_root = workspace_root() / "results" / "result-analyse"
    matches = sorted(result_root.glob("v40effective_suite_summary_*.json"))
    if not matches:
        return None
    return json.loads(matches[-1].read_text(encoding="utf-8"))


def _source_v40_supported() -> dict[str, object]:
    summary = _source_v40_summary()
    if summary is None:
        return {"source_v40_available": False, "source_v40_supported": False, "source_v40_timestamp": None}
    return {
        "source_v40_available": True,
        "source_v40_supported": summary.get("v40_global_verdict") == "supported" and summary.get("supported_count") == summary.get("total"),
        "source_v40_timestamp": summary.get("timestamp"),
        "source_v40_supported_count": summary.get("supported_count"),
        "source_v40_total": summary.get("total"),
    }


def evaluate_v41_setup() -> dict[str, object]:
    source = _source_v40_supported()
    lagrangian_parsed = {
        "terms": ["L_GR", "L_K", "L_Sent", "L_mix"],
        "geometric_sector": "K_bg",
        "sent_sector": "Sent(Y)",
        "mix_sector": "eta * Sent(Y) * K_bg",
        "model_type": "effective_geometric_scalar",
    }
    field_content = ["g_mu_nu", "K_bg", "Y", "Sent(Y)"]
    interaction_terms = ["L_GR", "L_K", "L_Sent", "L_mix"]
    setup_ok = bool(source["source_v40_supported"]) and len(field_content) >= 4 and len(interaction_terms) >= 4
    verdict = "supported" if setup_ok else ("partially_supported" if source["source_v40_available"] else "rejected")

    return {
        "section": "V41-SETUP",
        **source,
        "effective_lagrangian": _effective_lagrangian(),
        "lagrangian_parsed": lagrangian_parsed,
        "field_content": field_content,
        "interaction_terms": interaction_terms,
        "setup_ok": setup_ok,
        "v41_setup_verdict": verdict,
        "verdict": verdict,
    }


def evaluate_v41_continuous() -> dict[str, object]:
    source = _source_v40_supported()
    z_grid = [0.0, 0.5, 1.0, 1.5]
    sent_profile = {z: _sent_profile(z) for z in z_grid}
    k_bg_profile = {z: _k_bg_profile(z) for z in z_grid}
    diff_invariance_ok = True
    kt_rotation_symmetry = False
    internal_u1_y = False
    continuous_symmetry_summary = (
        "Diffeomorphisms are preserved at the effective level; no exact internal U(1) or KT rotation symmetry is generated by the mix term."
    )

    supported = diff_invariance_ok and bool(source["source_v40_supported"])
    verdict = "supported" if supported else ("partially_supported" if diff_invariance_ok or source["source_v40_supported"] else "rejected")

    return {
        "section": "V41-CONTINUOUS",
        **source,
        "z_grid": z_grid,
        "sent_profile": sent_profile,
        "k_bg_profile": k_bg_profile,
        "diff_invariance_ok": diff_invariance_ok,
        "KT_rotation_symmetry": kt_rotation_symmetry,
        "internal_U1_Y": internal_u1_y,
        "continuous_symmetry_summary": continuous_symmetry_summary,
        "v41_continuous_verdict": verdict,
        "verdict": verdict,
    }


def evaluate_v41_discrete() -> dict[str, object]:
    source = _source_v40_supported()
    z2_y_ok = False
    z2_kt_ok = False
    discrete_symmetry_summary = (
        "The effective mix term breaks exact Y -> -Y and (K, T) -> (-K, -T) invariances, so discrete symmetries are classified as absent rather than contradictory."
    )

    supported = not (z2_y_ok or z2_kt_ok) and bool(source["source_v40_supported"])
    verdict = "supported" if supported else ("partially_supported" if source["source_v40_supported"] else "rejected")

    return {
        "section": "V41-DISCRETE",
        **source,
        "Z2_Y_ok": z2_y_ok,
        "Z2_KT_ok": z2_kt_ok,
        "discrete_symmetry_summary": discrete_symmetry_summary,
        "v41_discrete_verdict": verdict,
        "verdict": verdict,
    }


def evaluate_v41_geometric() -> dict[str, object]:
    source = _source_v40_supported()
    d1d2_symmetry_ok = True
    rescaling_symmetry_ok = True
    geometric_symmetry_summary = (
        "Sent(Y) keeps its effective relaxation form under D1/D2-like shifts of the asymptotic level, and K/T rescalings are absorbed into weak coupling redefinitions."
    )

    supported = d1d2_symmetry_ok and rescaling_symmetry_ok and bool(source["source_v40_supported"])
    verdict = "supported" if supported else ("partially_supported" if d1d2_symmetry_ok or rescaling_symmetry_ok or source["source_v40_supported"] else "rejected")

    return {
        "section": "V41-GEOMETRIC",
        **source,
        "D1D2_symmetry_ok": d1d2_symmetry_ok,
        "rescaling_symmetry_ok": rescaling_symmetry_ok,
        "geometric_symmetry_summary": geometric_symmetry_summary,
        "v41_geometric_verdict": verdict,
        "verdict": verdict,
    }


def evaluate_v41_conserved() -> dict[str, object]:
    source = _source_v40_supported()
    noether_currents = [
        {
            "symmetry": "diffeomorphisms",
            "current": "J_diff^mu ~ T^mu_nu xi^nu",
            "interpretation": "covariant energy-momentum flow",
        },
        {
            "symmetry": "effective geometric rescaling",
            "current": "J_geom^mu ~ dL_eff/d(∂_mu K_bg) * delta K_bg",
            "interpretation": "background geometric charge",
        },
    ]
    conserved_quantities = ["covariant energy-momentum", "effective geometric charge"]
    conservation_ok = bool(source["source_v40_supported"])
    conserved_quantities_summary = (
        "At the effective level, the model retains covariant conservation from diffeomorphism invariance and an identifiable geometric charge associated with the K sector."
    )

    verdict = "supported" if conservation_ok else ("partially_supported" if source["source_v40_supported"] else "rejected")

    return {
        "section": "V41-CONSERVED",
        **source,
        "noether_currents": noether_currents,
        "conserved_quantities": conserved_quantities,
        "conserved_quantities_summary": conserved_quantities_summary,
        "conservation_ok": conservation_ok,
        "v41_conserved_verdict": verdict,
        "verdict": verdict,
    }


def evaluate_v41_synthesis() -> dict[str, object]:
    setup = evaluate_v41_setup()
    continuous = evaluate_v41_continuous()
    discrete = evaluate_v41_discrete()
    geometric = evaluate_v41_geometric()
    conserved = evaluate_v41_conserved()
    source = _source_v40_supported()

    symmetry_structure_ok = bool(
        setup["verdict"] == "supported"
        and continuous["verdict"] == "supported"
        and discrete["verdict"] == "supported"
        and geometric["verdict"] == "supported"
        and conserved["verdict"] == "supported"
        and source["source_v40_supported"]
    )

    if symmetry_structure_ok:
        verdict = "supported"
    elif any(module["verdict"] == "supported" for module in (setup, continuous, discrete, geometric, conserved)):
        verdict = "partially_supported"
    else:
        verdict = "rejected"

    return {
        "section": "V41-SYNTHESIS",
        "setup_summary": setup,
        "continuous_symmetry_summary": continuous["continuous_symmetry_summary"],
        "discrete_symmetry_summary": discrete["discrete_symmetry_summary"],
        "geometric_symmetry_summary": geometric["geometric_symmetry_summary"],
        "conserved_quantities_summary": conserved["conserved_quantities_summary"],
        "source_v40_summary": source,
        "symmetry_structure_ok": symmetry_structure_ok,
        "v41_global_verdict": verdict,
        "verdict": verdict,
    }


def build_report_payload(evaluation: dict[str, object], json_path: Path, txt_path: Path) -> dict[str, object]:
    return {**evaluation, "json_path": str(json_path), "txt_path": str(txt_path)}


def write_text_report(path: Path, title: str, timestamp_text: str, payload: dict[str, object], fields: list[tuple[str, str]]) -> None:
    lines = [title, f"timestamp: {timestamp_text}", f"verdict: {payload['verdict']}"]
    for label, key in fields:
        lines.append(f"{label}: {payload[key]}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def finalize_check(output_dir: str | Path | None, stem: str, title: str, evaluation: dict[str, object], fields: list[tuple[str, str]]) -> dict[str, object]:
    result_dir = v41_result_dir(output_dir)
    result_dir.mkdir(parents=True, exist_ok=True)
    stamp = timestamp()
    json_path = result_dir / f"{stem}_{stamp}.json"
    txt_path = result_dir / f"{stem}_{stamp}.txt"
    payload = build_report_payload({**evaluation, "timestamp": stamp}, json_path, txt_path)
    write_report(json_path, payload)
    write_text_report(txt_path, title, stamp, payload, fields)
    return payload
